@base_url = http://localhost:4000
@user_email = test@example.com
@user_password = PasswordSicura123
@auth_token = 

### 1. Registrazione (POST /api/register)
POST {{base_url}}/api/register
Content-Type: application/json

{
    "username": "UtenteTest",
    "email": "{{user_email}}",
    "password": "{{user_password}}"
}

--- 
### 2. Login (POST /api/login)
POST {{base_url}}/api/login
Content-Type: application/json

{
    "email": "{{user_email}}",
    "password": "{{user_password}}"
}

@auth_token = {{$response.body.token}} 

---
### 3. Logout (POST /api/logout)
POST {{base_url}}/api/logout
Authorization: Bearer {{auth_token}}